site_name: Cookiecutter Data Science @ Nesta
site_description: A project template and directory structure for Nesta Python data science projects.
repo_url: https://github.com/nestauk/cookiecutter-data-science-nesta
edit_uri: edit/master/docs/docs
copyright: Adapted from the <a href="http://drivendata.github.io/cookiecutter-data-science/">Drivendata data science cookiecutter</a>
theme:
  name: cinder
  disable_nav_previous_next: true
  disable_footer: false
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Guide: structure.md
  - FAQ: faq.md
